### ISSUE TITLE
Spotube crashes/exits after playing few songs

### ISSUE THREAD

**Issue by ghost** [KRTirtho/spotube#442]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After listening to few songs Spotube crashes when next song is supposed to start playing.

### Expected Behavior

Expect to start playing the next song.

### Steps to reproduce

Occurs appimage installation method. 
1. Open/run the app
2. Select some playlist
3. Listen to few songs from it
4. Crashes after listening for a while upon starting to play next song

### Operating System

Linux

### Spotube version

v2.7.0

### Installation source

GitHub Releases (Binary)

### Additional information

End of the terminal log when ran the appimage.
```flutter: Spotify API rate exceeded. waiting for 1 seconds
flutter: Spotify API rate exceeded. waiting for 1 seconds
flutter: Spotify API rate exceeded. waiting for 1 seconds
flutter: Spotify API rate exceeded. waiting for 1 seconds
flutter: Spotify API rate exceeded. waiting for 1 seconds
flutter: Spotify API rate exceeded. waiting for 1 seconds
flutter: Spotify API rate exceeded. waiting for 1 seconds
flutter: Spotify API rate exceeded. waiting for 1 seconds
flutter: Spotify API rate exceeded. waiting for 1 seconds
flutter: Spotify API rate exceeded. waiting for 1 seconds
flutter: Spotify API rate exceeded. waiting for 1 seconds
flutter: Spotify API rate exceeded. waiting for 1 seconds
flutter: Spotify API rate exceeded. waiting for 1 seconds
flutter: Spotify API rate exceeded. waiting for 1 seconds
flutter: Spotify API rate exceeded. waiting for 1 seconds
flutter: Spotify API rate exceeded. waiting for 1 seconds
flutter: Spotify API rate exceeded. waiting for 1 seconds
flutter: Spotify API rate exceeded. waiting for 1 seconds
flutter: Spotify API rate exceeded. waiting for 1 seconds
flutter: Spotify API rate exceeded. waiting for 1 seconds
flutter: Spotify API rate exceeded. waiting for 1 seconds
flutter: Spotify API rate exceeded. waiting for 1 seconds
flutter: Spotify API rate exceeded. waiting for 1 seconds
flutter: Spotify API rate exceeded. waiting for 1 seconds
AudioPlayers: Could not set playback to position 0 and rate 1,000000.
Failed to load cookie file from cookie: Too many open files
AudioPlayers: Could not query current position.
AudioPlayers: Could not query current duration.
AudioPlayers: Could not query current duration.
AudioPlayers: Could not query current duration.
AudioPlayers: Could not query current duration.
flutter: Spotify API rate exceeded. waiting for 1 seconds
flutter: Spotify API rate exceeded. waiting for 1 seconds
AudioPlayers: Could not query current duration.
AudioPlayers: Could not query current duration.
AudioPlayers: Could not query current duration.
AudioPlayers: Could not query current duration.
The per-process limit on the number of open file descriptors has been reached.
ERROR: cannot create wakeup pipe

(spotube:22836): GStreamer-WARNING **: 12:05:40.307: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstalsa.so': /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstalsa.so: cannot open shared object file: Too many open files

(spotube:22836): GStreamer-CRITICAL **: 12:05:40.307: gst_element_factory_create_valist: assertion 'newfactory != NULL' failed

(spotube:22836): GStreamer-WARNING **: 12:05:40.307: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstjack.so': /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstjack.so: cannot open shared object file: Too many open files

(spotube:22836): GStreamer-CRITICAL **: 12:05:40.307: gst_element_factory_create_valist: assertion 'newfactory != NULL' failed

(spotube:22836): GStreamer-WARNING **: 12:05:40.307: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstoss4.so': /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstoss4.so: cannot open shared object file: Too many open files

(spotube:22836): GStreamer-CRITICAL **: 12:05:40.307: gst_element_factory_create_valist: assertion 'newfactory != NULL' failed

(spotube:22836): GStreamer-WARNING **: 12:05:40.307: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstossaudio.so': /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstossaudio.so: cannot open shared object file: Too many open files

(spotube:22836): GStreamer-CRITICAL **: 12:05:40.307: gst_element_factory_create_valist: assertion 'newfactory != NULL' failed
AudioPlayers: Could not query current position.
AudioPlayers: Could not query current duration.
AudioPlayers: Could not query current position.
AudioPlayers: Could not query current duration.
AudioPlayers: Could not query current duration.
AudioPlayers: Could not set playback to position 10000 and rate 1,000000.
AudioPlayers: Could not query current duration.
AudioPlayers: Could not query current duration.
AudioPlayers: Could not query current duration.
flutter: Spotify API rate exceeded. waiting for 1 seconds
flutter: Spotify API rate exceeded. waiting for 1 seconds
flutter: Spotify API rate exceeded. waiting for 1 seconds
AudioPlayers: Could not query current duration.
AudioPlayers: Could not query current duration.
AudioPlayers: Could not query current duration.
AudioPlayers: Could not query current duration.
AudioPlayers: Could not set playback to position 10000 and rate 1,000000.
AudioPlayers: Could not set playback to position 10000 and rate 1,000000.
flutter: Spotify API rate exceeded. waiting for 1 seconds
flutter: Spotify API rate exceeded. waiting for 1 seconds
flutter: Spotify API rate exceeded. waiting for 1 seconds
flutter: Spotify API rate exceeded. waiting for 1 seconds

(spotube:22836): GLib-ERROR **: 12:05:40.445: Creating pipes for GWakeup: Too many open files
Trace/breakpoint trap (core dumped)
```

**Comment by gl4d** [comment]
got the same problem, the app gets stuck whenever it loads a new song.
it even makes the whole android interface crash and restart

never happened before, only with this current version.

**Comment by isle9** [comment]
This might somehow be related to my problem too. Spotube memory consumption seems to skyrocket after a few minutes. I saw it go up to 14gGB.

**Comment by KRTirtho** [comment]
There's a `.spotube_logs` file located in the User Documents directory or the User directory. Please submit this here, it should contain any error logs

Or you can always run spotube from the terminal with the `--verbose ` and submit the error logs here while reproducing the issue

**Comment by xenicx** [comment]
[spotube_logs.txt](https://github.com/KRTirtho/spotube/files/10988910/spotube_logs.txt)
Here is the log file and on terminal it gave this 
![image](https://user-images.githubusercontent.com/96352460/225572363-45a5aee1-a92a-4a06-927c-207117dcd513.png)

**Comment by Aro320x** [comment]
> habe das gleiche Problem auf meinem OP6, die App bleibt hängen, wenn sie einen neuen Song lädt. Es lässt sogar die gesamte Android-Oberfläche abstürzen und neu starten
> 
> noch nie passiert, nur mit dieser aktuellen Version.

Bei mir genau das selbe Problem!
Xiaomi redmi note 10 pro

**Comment by KRTirtho** [comment]
It has been fixed yesterday by https://github.com/KRTirtho/spotube/commit/09b24cf1fd1644c549f85904545db54b39cc2431
Apparently, the progress bar (2) and a special utility `useBreakpoints` was causing all this issue due to excessive re-renders

The fix is of course available on nightly and will be released soon

**Comment by RaptaG** [comment]
Fixed in 3.0.0

**Comment by systemoperator** [comment]
> It has been fixed yesterday by [09b24cf](https://github.com/KRTirtho/spotube/commit/09b24cf1fd1644c549f85904545db54b39cc2431) Apparently, the progress bar (2) and a special utility `useBreakpoints` was causing all this issue due to excessive re-renders
> 
> The fix is of course available on nightly and will be released soon

@KRTirtho @RaptaG Unfortunately, the application still has this issue on Debian 11. It fills up all available memory until either the OS or the application crashes. Initially, the OS tries to compensate the memory greediness by filling up all RAM and swap space, after that, the OS gets unusable. And this happens with 32 GB of RAM and 16 GB swap space. I hoped, it would be fixed. So I finally tried it with version 3.0.0, but after running the app for about 10 minutes, playing music, the music stops unexpectedly and the OS is unresponsive and unusable again. :cry:

**Comment by KRTirtho** [comment]
@systemoperator v3.0.1 is released with a fix (https://github.com/KRTirtho/spotube/pull/606)
Please check if you're still having that performance issue

**Comment by systemoperator** [comment]
> @systemoperator v3.0.1 is released with a fix (#606) Please check if you're still having that performance issue

@KRTirtho The performance issue seems gone now :smiley: 

![image](https://github.com/KRTirtho/spotube/assets/3658393/41703bfc-b39d-4567-adf1-7468e1bdb3d9)

Furthermore, I currently have no problem with the extreme memory-greediness mentioned in #442. It's the first time ever, that I can play 4+ songs in a row, without crashing the os. :)

One issue remains though: Rather often, the music doesn't start playing, independet of, what I want to play (my playlist, one selected track, recommended tracks and so on).

The logs are:

```
% flatpak run com.github.KRTirtho.Spotube
Gtk-Message: 20:21:04.553: Failed to load module "gtk-vector-screenshot"
Gtk-Message: 20:21:04.554: Failed to load module "canberra-gtk-module"

** (spotube:2): CRITICAL **: 20:21:05.097: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found

** (spotube:2): CRITICAL **: 20:21:05.103: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found
package:media_kit_libs_linux registered.
flutter: media_kit: WARNING: package:media_kit_native_event_loop not found.

(process:3150456): GLib-GIO-WARNING **: 20:21:08.002: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:21:08.057: Socket check failed

** (process:3150456): WARNING **: 20:21:08.081: Error writing credentials to socket: Error sending message: Broken pipe

(process:3150456): GLib-GIO-WARNING **: 20:21:08.529: Socket check failed

** (process:3150456): WARNING **: 20:21:08.558: Error writing credentials to socket: Socket is already closed

(process:3150456): GLib-GIO-WARNING **: 20:21:08.583: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:21:10.373: Socket check failed
flutter: PostgrestException(message: duplicate key value violates unique constraint "tracks_youtube_id_spotify_id_idx", code: 23505, details: Conflict, hint: null)
flutter: #0      PostgrestBuilder._parseResponse (package:postgrest/src/postgrest_builder.dart:323)
flutter: #1      PostgrestBuilder._execute (package:postgrest/src/postgrest_builder.dart:198)
flutter: <asynchronous suspension>
flutter: #2      PostgrestBuilder.then (package:postgrest/src/postgrest_builder.dart:400)
flutter: <asynchronous suspension>
flutter: PostgrestException(message: duplicate key value violates unique constraint "tracks_youtube_id_spotify_id_idx", code: 23505, details: Conflict, hint: null)
flutter: #0      PostgrestBuilder._parseResponse (package:postgrest/src/postgrest_builder.dart:323)
flutter: #1      PostgrestBuilder._execute (package:postgrest/src/postgrest_builder.dart:198)
flutter: <asynchronous suspension>
flutter: #2      PostgrestBuilder.then (package:postgrest/src/postgrest_builder.dart:400)
flutter: <asynchronous suspension>
flutter: PostgrestException(message: duplicate key value violates unique constraint "tracks_youtube_id_spotify_id_idx", code: 23505, details: Conflict, hint: null)
flutter: #0      PostgrestBuilder._parseResponse (package:postgrest/src/postgrest_builder.dart:323)
flutter: #1      PostgrestBuilder._execute (package:postgrest/src/postgrest_builder.dart:198)
flutter: <asynchronous suspension>
flutter: #2      PostgrestBuilder.then (package:postgrest/src/postgrest_builder.dart:400)
flutter: <asynchronous suspension>
flutter: PostgrestException(message: duplicate key value violates unique constraint "tracks_youtube_id_spotify_id_idx", code: 23505, details: Conflict, hint: null)
flutter: #0      PostgrestBuilder._parseResponse (package:postgrest/src/postgrest_builder.dart:323)
flutter: #1      PostgrestBuilder._execute (package:postgrest/src/postgrest_builder.dart:198)
flutter: <asynchronous suspension>
flutter: #2      PostgrestBuilder.then (package:postgrest/src/postgrest_builder.dart:400)
flutter: <asynchronous suspension>

** (process:3150456): WARNING **: 20:31:56.486: Error writing credentials to socket: Socket is already closed
flutter: PostgrestException(message: duplicate key value violates unique constraint "tracks_youtube_id_spotify_id_idx", code: 23505, details: Conflict, hint: null)
flutter: #0      PostgrestBuilder._parseResponse (package:postgrest/src/postgrest_builder.dart:323)
flutter: #1      PostgrestBuilder._execute (package:postgrest/src/postgrest_builder.dart:198)
flutter: <asynchronous suspension>
flutter: #2      PostgrestBuilder.then (package:postgrest/src/postgrest_builder.dart:400)
flutter: <asynchronous suspension>
flutter: PostgrestException(message: duplicate key value violates unique constraint "tracks_youtube_id_spotify_id_idx", code: 23505, details: Conflict, hint: null)
flutter: #0      PostgrestBuilder._parseResponse (package:postgrest/src/postgrest_builder.dart:323)
flutter: #1      PostgrestBuilder._execute (package:postgrest/src/postgrest_builder.dart:198)
flutter: <asynchronous suspension>
flutter: #2      PostgrestBuilder.then (package:postgrest/src/postgrest_builder.dart:400)
flutter: <asynchronous suspension>
flutter: PostgrestException(message: duplicate key value violates unique constraint "tracks_spotify_id_idx", code: 23505, details: Conflict, hint: null)
flutter: #0      PostgrestBuilder._parseResponse (package:postgrest/src/postgrest_builder.dart:323)
flutter: #1      PostgrestBuilder._execute (package:postgrest/src/postgrest_builder.dart:198)
flutter: <asynchronous suspension>
flutter: #2      PostgrestBuilder.then (package:postgrest/src/postgrest_builder.dart:400)
flutter: <asynchronous suspension>
flutter: PostgrestException(message: duplicate key value violates unique constraint "tracks_youtube_id_spotify_id_idx", code: 23505, details: Conflict, hint: null)
flutter: #0      PostgrestBuilder._parseResponse (package:postgrest/src/postgrest_builder.dart:323)
flutter: #1      PostgrestBuilder._execute (package:postgrest/src/postgrest_builder.dart:198)
flutter: <asynchronous suspension>
flutter: #2      PostgrestBuilder.then (package:postgrest/src/postgrest_builder.dart:400)
flutter: <asynchronous suspension>
flutter: PostgrestException(message: duplicate key value violates unique constraint "tracks_youtube_id_spotify_id_idx", code: 23505, details: Conflict, hint: null)
flutter: #0      PostgrestBuilder._parseResponse (package:postgrest/src/postgrest_builder.dart:323)
flutter: #1      PostgrestBuilder._execute (package:postgrest/src/postgrest_builder.dart:198)
flutter: <asynchronous suspension>
flutter: #2      PostgrestBuilder.then (package:postgrest/src/postgrest_builder.dart:400)
flutter: <asynchronous suspension>
flutter: PostgrestException(message: duplicate key value violates unique constraint "tracks_youtube_id_spotify_id_idx", code: 23505, details: Conflict, hint: null)
flutter: #0      PostgrestBuilder._parseResponse (package:postgrest/src/postgrest_builder.dart:323)
flutter: #1      PostgrestBuilder._execute (package:postgrest/src/postgrest_builder.dart:198)
flutter: <asynchronous suspension>
flutter: #2      PostgrestBuilder.then (package:postgrest/src/postgrest_builder.dart:400)
flutter: <asynchronous suspension>
flutter: PostgrestException(message: duplicate key value violates unique constraint "tracks_spotify_id_idx", code: 23505, details: Conflict, hint: null)
flutter: #0      PostgrestBuilder._parseResponse (package:postgrest/src/postgrest_builder.dart:323)
flutter: #1      PostgrestBuilder._execute (package:postgrest/src/postgrest_builder.dart:198)
flutter: <asynchronous suspension>
flutter: #2      PostgrestBuilder.then (package:postgrest/src/postgrest_builder.dart:400)
flutter: <asynchronous suspension>
flutter: PostgrestException(message: duplicate key value violates unique constraint "tracks_youtube_id_spotify_id_idx", code: 23505, details: Conflict, hint: null)
flutter: #0      PostgrestBuilder._parseResponse (package:postgrest/src/postgrest_builder.dart:323)
flutter: #1      PostgrestBuilder._execute (package:postgrest/src/postgrest_builder.dart:198)
flutter: <asynchronous suspension>
flutter: #2      PostgrestBuilder.then (package:postgrest/src/postgrest_builder.dart:400)
flutter: <asynchronous suspension>
```

**Comment by systemoperator** [comment]
@KRTirtho Hmm, and after a while, the music stops. Looking, why, shows, the application exited silently, as mentioned in this issue:

```
xxx@yyy ~ % flatpak run com.github.KRTirtho.Spotube
Gtk-Message: 20:21:04.553: Failed to load module "gtk-vector-screenshot"
Gtk-Message: 20:21:04.554: Failed to load module "canberra-gtk-module"

** (spotube:2): CRITICAL **: 20:21:05.097: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found

** (spotube:2): CRITICAL **: 20:21:05.103: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found
package:media_kit_libs_linux registered.
flutter: media_kit: WARNING: package:media_kit_native_event_loop not found.

(process:3150456): GLib-GIO-WARNING **: 20:21:08.002: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:21:08.057: Socket check failed

** (process:3150456): WARNING **: 20:21:08.081: Error writing credentials to socket: Error sending message: Broken pipe

(process:3150456): GLib-GIO-WARNING **: 20:21:08.529: Socket check failed

** (process:3150456): WARNING **: 20:21:08.558: Error writing credentials to socket: Socket is already closed

(process:3150456): GLib-GIO-WARNING **: 20:21:08.583: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:21:10.373: Socket check failed
flutter: PostgrestException(message: duplicate key value violates unique constraint "tracks_youtube_id_spotify_id_idx", code: 23505, details: Conflict, hint: null)
flutter: #0      PostgrestBuilder._parseResponse (package:postgrest/src/postgrest_builder.dart:323)
flutter: #1      PostgrestBuilder._execute (package:postgrest/src/postgrest_builder.dart:198)
flutter: <asynchronous suspension>
flutter: #2      PostgrestBuilder.then (package:postgrest/src/postgrest_builder.dart:400)
flutter: <asynchronous suspension>
flutter: PostgrestException(message: duplicate key value violates unique constraint "tracks_youtube_id_spotify_id_idx", code: 23505, details: Conflict, hint: null)
flutter: #0      PostgrestBuilder._parseResponse (package:postgrest/src/postgrest_builder.dart:323)
flutter: #1      PostgrestBuilder._execute (package:postgrest/src/postgrest_builder.dart:198)
flutter: <asynchronous suspension>
flutter: #2      PostgrestBuilder.then (package:postgrest/src/postgrest_builder.dart:400)
flutter: <asynchronous suspension>
flutter: PostgrestException(message: duplicate key value violates unique constraint "tracks_youtube_id_spotify_id_idx", code: 23505, details: Conflict, hint: null)
flutter: #0      PostgrestBuilder._parseResponse (package:postgrest/src/postgrest_builder.dart:323)
flutter: #1      PostgrestBuilder._execute (package:postgrest/src/postgrest_builder.dart:198)
flutter: <asynchronous suspension>
flutter: #2      PostgrestBuilder.then (package:postgrest/src/postgrest_builder.dart:400)
flutter: <asynchronous suspension>
flutter: PostgrestException(message: duplicate key value violates unique constraint "tracks_youtube_id_spotify_id_idx", code: 23505, details: Conflict, hint: null)
flutter: #0      PostgrestBuilder._parseResponse (package:postgrest/src/postgrest_builder.dart:323)
flutter: #1      PostgrestBuilder._execute (package:postgrest/src/postgrest_builder.dart:198)
flutter: <asynchronous suspension>
flutter: #2      PostgrestBuilder.then (package:postgrest/src/postgrest_builder.dart:400)
flutter: <asynchronous suspension>

** (process:3150456): WARNING **: 20:31:56.486: Error writing credentials to socket: Socket is already closed
flutter: PostgrestException(message: duplicate key value violates unique constraint "tracks_youtube_id_spotify_id_idx", code: 23505, details: Conflict, hint: null)
flutter: #0      PostgrestBuilder._parseResponse (package:postgrest/src/postgrest_builder.dart:323)
flutter: #1      PostgrestBuilder._execute (package:postgrest/src/postgrest_builder.dart:198)
flutter: <asynchronous suspension>
flutter: #2      PostgrestBuilder.then (package:postgrest/src/postgrest_builder.dart:400)
flutter: <asynchronous suspension>
flutter: PostgrestException(message: duplicate key value violates unique constraint "tracks_youtube_id_spotify_id_idx", code: 23505, details: Conflict, hint: null)
flutter: #0      PostgrestBuilder._parseResponse (package:postgrest/src/postgrest_builder.dart:323)
flutter: #1      PostgrestBuilder._execute (package:postgrest/src/postgrest_builder.dart:198)
flutter: <asynchronous suspension>
flutter: #2      PostgrestBuilder.then (package:postgrest/src/postgrest_builder.dart:400)
flutter: <asynchronous suspension>
flutter: PostgrestException(message: duplicate key value violates unique constraint "tracks_spotify_id_idx", code: 23505, details: Conflict, hint: null)
flutter: #0      PostgrestBuilder._parseResponse (package:postgrest/src/postgrest_builder.dart:323)
flutter: #1      PostgrestBuilder._execute (package:postgrest/src/postgrest_builder.dart:198)
flutter: <asynchronous suspension>
flutter: #2      PostgrestBuilder.then (package:postgrest/src/postgrest_builder.dart:400)
flutter: <asynchronous suspension>
flutter: PostgrestException(message: duplicate key value violates unique constraint "tracks_youtube_id_spotify_id_idx", code: 23505, details: Conflict, hint: null)
flutter: #0      PostgrestBuilder._parseResponse (package:postgrest/src/postgrest_builder.dart:323)
flutter: #1      PostgrestBuilder._execute (package:postgrest/src/postgrest_builder.dart:198)
flutter: <asynchronous suspension>
flutter: #2      PostgrestBuilder.then (package:postgrest/src/postgrest_builder.dart:400)
flutter: <asynchronous suspension>
flutter: PostgrestException(message: duplicate key value violates unique constraint "tracks_youtube_id_spotify_id_idx", code: 23505, details: Conflict, hint: null)
flutter: #0      PostgrestBuilder._parseResponse (package:postgrest/src/postgrest_builder.dart:323)
flutter: #1      PostgrestBuilder._execute (package:postgrest/src/postgrest_builder.dart:198)
flutter: <asynchronous suspension>
flutter: #2      PostgrestBuilder.then (package:postgrest/src/postgrest_builder.dart:400)
flutter: <asynchronous suspension>
flutter: PostgrestException(message: duplicate key value violates unique constraint "tracks_youtube_id_spotify_id_idx", code: 23505, details: Conflict, hint: null)
flutter: #0      PostgrestBuilder._parseResponse (package:postgrest/src/postgrest_builder.dart:323)
flutter: #1      PostgrestBuilder._execute (package:postgrest/src/postgrest_builder.dart:198)
flutter: <asynchronous suspension>
flutter: #2      PostgrestBuilder.then (package:postgrest/src/postgrest_builder.dart:400)
flutter: <asynchronous suspension>
flutter: PostgrestException(message: duplicate key value violates unique constraint "tracks_spotify_id_idx", code: 23505, details: Conflict, hint: null)
flutter: #0      PostgrestBuilder._parseResponse (package:postgrest/src/postgrest_builder.dart:323)
flutter: #1      PostgrestBuilder._execute (package:postgrest/src/postgrest_builder.dart:198)
flutter: <asynchronous suspension>
flutter: #2      PostgrestBuilder.then (package:postgrest/src/postgrest_builder.dart:400)
flutter: <asynchronous suspension>
flutter: PostgrestException(message: duplicate key value violates unique constraint "tracks_youtube_id_spotify_id_idx", code: 23505, details: Conflict, hint: null)
flutter: #0      PostgrestBuilder._parseResponse (package:postgrest/src/postgrest_builder.dart:323)
flutter: #1      PostgrestBuilder._execute (package:postgrest/src/postgrest_builder.dart:198)
flutter: <asynchronous suspension>
flutter: #2      PostgrestBuilder.then (package:postgrest/src/postgrest_builder.dart:400)
flutter: <asynchronous suspension>

** (process:3150456): WARNING **: 20:51:44.017: Error writing credentials to socket: Error sending message: Broken pipe

(process:3150456): GLib-GIO-WARNING **: 20:51:44.122: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:51:44.146: Socket check failed

** (process:3150456): WARNING **: 20:51:44.281: Error writing credentials to socket: Socket is already closed

(process:3150456): GLib-GIO-WARNING **: 20:51:44.547: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:51:44.673: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:51:44.713: Socket check failed

** (process:3150456): WARNING **: 20:51:44.728: Error writing credentials to socket: Socket is already closed

** (process:3150456): WARNING **: 20:51:45.299: Error writing credentials to socket: Socket is already closed

(process:3150456): GLib-GIO-WARNING **: 20:51:45.314: Socket check failed

** (process:3150456): WARNING **: 20:51:45.341: Error writing credentials to socket: Socket is already closed

(process:3150456): GLib-GIO-WARNING **: 20:51:45.717: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:51:46.038: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:51:46.070: Socket check failed

** (process:3150456): WARNING **: 20:51:46.157: Error writing credentials to socket: Socket is already closed

(process:3150456): GLib-GIO-WARNING **: 20:51:46.471: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:51:46.556: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:51:46.644: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:55:26.824: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:55:26.900: Socket check failed

** (process:3150456): WARNING **: 20:55:27.053: Error writing credentials to socket: Error sending message: Broken pipe

(process:3150456): GLib-GIO-WARNING **: 20:55:27.064: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:55:27.170: Socket check failed

** (process:3150456): WARNING **: 20:55:27.683: Error writing credentials to socket: Socket is already closed

** (process:3150456): WARNING **: 20:55:27.696: Error writing credentials to socket: Socket is already closed

(process:3150456): GLib-GIO-WARNING **: 20:55:27.754: Socket check failed

** (process:3150456): WARNING **: 20:55:27.992: Error writing credentials to socket: Error sending message: Broken pipe

** (process:3150456): WARNING **: 20:55:28.003: Error writing credentials to socket: Socket is already closed

(process:3150456): GLib-GIO-WARNING **: 20:55:28.700: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:55:28.734: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:55:29.222: Socket check failed

** (process:3150456): WARNING **: 20:55:29.721: Error writing credentials to socket: Socket is already closed

(process:3150456): GLib-GIO-WARNING **: 20:55:30.674: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:55:30.686: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:55:30.840: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:55:30.920: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:55:30.934: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:55:30.945: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:55:31.254: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:55:31.265: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:55:31.277: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:55:31.376: Socket check failed

** (process:3150456): WARNING **: 20:55:32.058: Error writing credentials to socket: Socket is already closed

(process:3150456): GLib-GIO-WARNING **: 20:55:32.174: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:55:32.624: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:55:32.641: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:55:32.713: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:55:32.768: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:55:32.835: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:55:32.886: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:55:33.617: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:55:35.070: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:55:35.140: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:55:35.696: Socket check failed

** (process:3150456): WARNING **: 20:55:35.762: Error writing credentials to socket: Socket is already closed

(process:3150456): GLib-GIO-WARNING **: 20:55:36.351: Socket check failed

** (process:3150456): WARNING **: 20:55:36.743: Error writing credentials to socket: Socket is already closed

** (process:3150456): WARNING **: 20:55:36.772: Error writing credentials to socket: Error sending message: Broken pipe

(process:3150456): GLib-GIO-WARNING **: 20:55:39.103: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:55:39.883: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:55:40.582: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:55:40.593: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:55:41.707: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:55:42.451: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:55:42.496: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:55:42.507: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:55:43.422: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:55:46.658: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:55:46.756: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:55:47.859: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:55:47.933: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:55:48.091: Socket check failed

** (process:3150456): WARNING **: 20:55:48.708: Error writing credentials to socket: Error sending message: Broken pipe

(process:3150456): GLib-GIO-WARNING **: 20:55:48.750: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:55:49.002: Socket check failed

** (process:3150456): WARNING **: 20:55:49.896: Error writing credentials to socket: Socket is already closed

(process:3150456): GLib-GIO-WARNING **: 20:55:49.952: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:55:51.433: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:55:51.459: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:55:51.581: Socket check failed

** (process:3150456): WARNING **: 20:55:52.419: Error writing credentials to socket: Socket is already closed

** (process:3150456): WARNING **: 20:55:53.716: Error writing credentials to socket: Error sending message: Broken pipe

(process:3150456): GLib-GIO-WARNING **: 20:55:55.754: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:55:55.800: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:55:57.062: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:55:58.617: Socket check failed

** (process:3150456): WARNING **: 20:55:59.915: Error writing credentials to socket: Error sending message: Broken pipe

** (process:3150456): WARNING **: 20:56:00.067: Error writing credentials to socket: Socket is already closed

(process:3150456): GLib-GIO-WARNING **: 20:56:03.120: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:56:03.144: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:56:04.660: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:56:05.710: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:56:05.822: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:56:05.838: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:56:05.850: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:56:05.875: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:56:05.886: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:56:05.908: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:56:07.783: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:56:09.438: Socket check failed

** (process:3150456): WARNING **: 20:56:10.819: Error writing credentials to socket: Error sending message: Broken pipe

(process:3150456): GLib-GIO-WARNING **: 20:56:14.625: Socket check failed

** (process:3150456): WARNING **: 20:56:18.353: Error writing credentials to socket: Error sending message: Broken pipe

(process:3150456): GLib-GIO-WARNING **: 20:56:24.826: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:56:28.558: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:56:28.574: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:56:28.711: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:56:28.722: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:56:28.735: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:56:28.780: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:56:33.479: Socket check failed
flutter: Connection failed
flutter: #0      IOClient.send (package:http/src/io_client.dart:88)
flutter: <asynchronous suspension>
flutter: #1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93)
flutter: <asynchronous suspension>
flutter: #2      _withClient (package:http/http.dart:164)
flutter: <asynchronous suspension>
flutter: #3      PostgrestBuilder._execute (package:postgrest/src/postgrest_builder.dart:169)
flutter: <asynchronous suspension>
flutter: #4      PostgrestBuilder.then (package:postgrest/src/postgrest_builder.dart:400)
flutter: <asynchronous suspension>

(process:3150456): GLib-GIO-WARNING **: 20:56:35.560: Socket check failed

** (process:3150456): WARNING **: 20:56:38.170: Error writing credentials to socket: Error sending message: Broken pipe

(process:3150456): GLib-GIO-WARNING **: 20:56:43.086: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:56:44.739: Socket check failed

** (process:3150456): WARNING **: 20:56:44.894: Error writing credentials to socket: Socket is already closed

(process:3150456): GLib-GIO-WARNING **: 20:56:44.916: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:56:44.937: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:56:49.712: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:56:49.738: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:56:49.771: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:56:49.787: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:56:51.173: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:56:51.185: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:56:51.241: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:56:51.254: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:56:56.773: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:56:56.803: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:56:58.278: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:57:05.024: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:57:05.049: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:57:05.120: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:57:09.283: Socket check failed

(process:3150456): GLib-GIO-WARNING **: 20:57:10.718: Socket check failed

** (process:3150456): WARNING **: 20:57:10.773: Error writing credentials to socket: Socket is already closed

** (process:3150456): WARNING **: 20:57:16.487: Error writing credentials to socket: Socket is already closed

** (process:3150456): WARNING **: 20:57:34.627: Error writing credentials to socket: Error sending message: Broken pipe
137 xxx@yyy ~ %
```

**Comment by systemoperator** [comment]
@KRTirtho I found the reason for exiting:

```
Aug  6 21:04:23 yyy kernel: [279221.515507] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=user.slice,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/user@1000.service/app.slice/app-flatpak-com.github.KRTirtho.Spotube-3150450.scope,task=spotube,pid=3150464,uid=1000
Aug  6 21:04:23 w520 kernel: [279221.515620] Out of memory: Killed process 3150464 (spotube) total-vm:23475972kB, anon-rss:19571704kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:54852kB oom_score_adj:0
Aug  6 21:04:25 w520 kernel: [279223.932100] oom_reaper: reaped process 3150464 (spotube), now anon-rss:16kB, file-rss:0kB, shmem-rss:0kB

Priority: 3
```

**Comment by systemoperator** [comment]
> @systemoperator v3.0.1 is released with a fix (#606) Please check if you're still having that performance issue

@KRTirtho Unfortunately, also the performance issue came back after a while:

![image](https://github.com/KRTirtho/spotube/assets/3658393/06753fbc-a95e-46f6-8229-44cd885325d3)

**Comment by roberto68** [comment]
> There's a `.spotube_logs` file located in the User Documents directory or the User directory. Please submit this here, it should contain any error logs
> 
> Or you can always run spotube from the terminal with the `--verbose ` and submit the error logs here while reproducing the issue

I can't find either `spotube_logs` dir or `spotube_logs.txt` file and neither can I ran spotube from cmd line (cause of flatpak) is it possible to specify it via the GUI or do I've to use AppImage or install via source (tar)?

**Comment by systemoperator** [comment]
> > There's a `.spotube_logs` file located in the User Documents directory or the User directory. Please submit this here, it should contain any error logs
> > Or you can always run spotube from the terminal with the `--verbose ` and submit the error logs here while reproducing the issue
> 
> I can't find either `spotube_logs` dir or `spotube_logs.txt` file and neither can I ran spotube from cmd line (cause of flatpak?) is it possible to find the logging info (or location of log files) via GUI or do I've to use AppImage or install via source (tar)?

You can run `flatpak run com.github.KRTirtho.Spotube --verbose` from terminal. :)

**Comment by systemoperator** [comment]
I have always problems with starting a song at all, maybe this reveals some details. Some crashes are mentioned.

```
flatpak run com.github.KRTirtho.Spotube --verbose
Gtk-Message: 13:40:04.268: Failed to load module "gtk-vector-screenshot"
Gtk-Message: 13:40:04.270: Failed to load module "canberra-gtk-module"

** (spotube:2): CRITICAL **: 13:40:04.914: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found

** (spotube:2): CRITICAL **: 13:40:04.926: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found
package:media_kit_libs_linux registered.
flutter: media_kit: WARNING: package:media_kit_native_event_loop not found.
flutter: [2023-08-08 13:40:06.533836 | Catcher | WARNING] Screenshots path is empty. Screenshots won't work.
flutter: [2023-08-08 13:40:06.534170 | Catcher | FINE] Catcher configured successfully.
flutter: [2023-08-08 13:40:06.559649 | GoRouter | INFO] Full paths for routes:
  => /mini-player
  => /login
  => /login-tutorial
  => /player
known full paths for route names:
  search => /search
  library => /library
  lyrics => /lyrics

flutter: [2023-08-08 13:40:06.563720 | GoRouter | INFO] Using MaterialApp configuration

(process:3958419): GLib-GIO-WARNING **: 13:40:07.831: Socket check failed
flutter: [2023-08-08 13:40:08.080069 | Catcher | INFO] Setup localization lazily!
flutter: [2023-08-08 13:40:08.080312 | Catcher | INFO] ============================== CATCHER LOG ==============================
flutter: [2023-08-08 13:40:08.080418 | Catcher | INFO] Crash occurred on 2023-08-08 13:40:08.080236
flutter: [2023-08-08 13:40:08.080457 | Catcher | INFO] 
flutter: [2023-08-08 13:40:08.080498 | Catcher | INFO] ------- DEVICE INFO -------
flutter: [2023-08-08 13:40:08.080550 | Catcher | INFO] name: GNOME
flutter: [2023-08-08 13:40:08.080586 | Catcher | INFO] version: 44 (Flatpak runtime)
flutter: [2023-08-08 13:40:08.080617 | Catcher | INFO] id: org.gnome.Platform
flutter: [2023-08-08 13:40:08.080651 | Catcher | INFO] idLike: null
flutter: [2023-08-08 13:40:08.080687 | Catcher | INFO] versionCodename: null
flutter: [2023-08-08 13:40:08.080717 | Catcher | INFO] versionId: 44
flutter: [2023-08-08 13:40:08.080735 | Catcher | INFO] prettyName: GNOME 44 (Flatpak runtime)
flutter: [2023-08-08 13:40:08.080753 | Catcher | INFO] buildId: null
flutter: [2023-08-08 13:40:08.080770 | Catcher | INFO] variant: null
flutter: [2023-08-08 13:40:08.080792 | Catcher | INFO] variantId: null
flutter: [2023-08-08 13:40:08.080821 | Catcher | INFO] machineId: dbfc52975aed46dcab33b235bc7f0310
flutter: [2023-08-08 13:40:08.080845 | Catcher | INFO] 
flutter: [2023-08-08 13:40:08.080871 | Catcher | INFO] ------- APP INFO -------
flutter: [2023-08-08 13:40:08.080905 | Catcher | INFO] environment: release
flutter: [2023-08-08 13:40:08.080934 | Catcher | INFO] version: 3.0.1
flutter: [2023-08-08 13:40:08.080977 | Catcher | INFO] appName: spotube
flutter: [2023-08-08 13:40:08.081016 | Catcher | INFO] buildNumber: 20
flutter: [2023-08-08 13:40:08.081052 | Catcher | INFO] packageName: spotube
flutter: [2023-08-08 13:40:08.081084 | Catcher | INFO] 
flutter: [2023-08-08 13:40:08.081129 | Catcher | INFO] ---------- ERROR ----------
flutter: [2023-08-08 13:40:08.081172 | Catcher | INFO] PathNotFoundException: Cannot open file, path = '/home/stefan/.var/app/com.github.KRTirtho.Spotube/config/dconf/user' (OS Error: No such file or directory, errno = 2)
flutter: [2023-08-08 13:40:08.081200 | Catcher | INFO] 
flutter: [2023-08-08 13:40:08.081225 | Catcher | INFO] ------- STACK TRACE -------
flutter: [2023-08-08 13:40:08.081383 | Catcher | INFO] #0      _checkForErrorResponse (dart:io/common.dart:55)
flutter: [2023-08-08 13:40:08.081414 | Catcher | INFO] #1      _File.open.<anonymous closure> (dart:io/file_impl.dart:381)
flutter: [2023-08-08 13:40:08.081443 | Catcher | INFO] <asynchronous suspension>
flutter: [2023-08-08 13:40:08.081468 | Catcher | INFO] #2      GVariantDatabase._loadRootTable (package:gsettings/src/gvariant_database.dart:30)
flutter: [2023-08-08 13:40:08.081499 | Catcher | INFO] <asynchronous suspension>
flutter: [2023-08-08 13:40:08.081526 | Catcher | INFO] #3      GVariantDatabase.lookup (package:gsettings/src/gvariant_database.dart:20)
flutter: [2023-08-08 13:40:08.081553 | Catcher | INFO] <asynchronous suspension>
flutter: [2023-08-08 13:40:08.081576 | Catcher | INFO] #4      DConfClient.read (package:gsettings/src/dconf_client.dart:82)
flutter: [2023-08-08 13:40:08.081604 | Catcher | INFO] <asynchronous suspension>
flutter: [2023-08-08 13:40:08.081629 | Catcher | INFO] #5      GSettingsDConfBackend.get (package:gsettings/src/gsettings_dconf_backend.dart:23)
flutter: [2023-08-08 13:40:08.081656 | Catcher | INFO] <asynchronous suspension>
flutter: [2023-08-08 13:40:08.081681 | Catcher | INFO] #6      GSettings.get (package:gsettings/src/gsettings.dart:117)
flutter: [2023-08-08 13:40:08.081706 | Catcher | INFO] <asynchronous suspension>
flutter: [2023-08-08 13:40:08.081730 | Catcher | INFO] #7      getTheme (package:titlebar_buttons/src/get_theme.dart:12)
flutter: [2023-08-08 13:40:08.081755 | Catcher | INFO] <asynchronous suspension>
flutter: [2023-08-08 13:40:08.081779 | Catcher | INFO] 
flutter: [2023-08-08 13:40:08.081803 | Catcher | INFO] ======================================================================
flutter: [2023-08-08 13:40:08.082015 | Catcher | INFO] Report result: true
flutter: [2023-08-08 13:40:08.082590 | Catcher | FINE] Error: 'PathNotFoundException: Cannot open file, path = '/home/stefan/.var/app/com.github.KRTirtho.Spotube/config/dconf/user' (OS Error: No such file or directory, errno = 2)' has been skipped to due to duplication occurence within 3000 ms.
flutter: [2023-08-08 13:40:08.082952 | Catcher | FINE] Error: 'PathNotFoundException: Cannot open file, path = '/home/stefan/.var/app/com.github.KRTirtho.Spotube/config/dconf/user' (OS Error: No such file or directory, errno = 2)' has been skipped to due to duplication occurence within 3000 ms.

(process:3958419): GLib-GIO-WARNING **: 13:40:08.130: Socket check failed

(process:3958419): GLib-GIO-WARNING **: 13:40:08.206: Socket check failed
flutter: [2023-08-08 13:40:08.303400 | Catcher | INFO] Report result: true

** (process:3958419): WARNING **: 13:40:08.385: Error writing credentials to socket: Error sending message: Broken pipe

(process:3958419): GLib-GIO-WARNING **: 13:40:08.400: Socket check failed
flutter: [2023-08-08 13:40:08.522267 | Catcher | INFO] ============================== CATCHER LOG ==============================
flutter: [2023-08-08 13:40:08.522357 | Catcher | INFO] Crash occurred on 2023-08-08 13:40:08.522206
flutter: [2023-08-08 13:40:08.522391 | Catcher | INFO] 
flutter: [2023-08-08 13:40:08.522417 | Catcher | INFO] ------- DEVICE INFO -------
flutter: [2023-08-08 13:40:08.522451 | Catcher | INFO] name: GNOME
flutter: [2023-08-08 13:40:08.522483 | Catcher | INFO] version: 44 (Flatpak runtime)
flutter: [2023-08-08 13:40:08.522510 | Catcher | INFO] id: org.gnome.Platform
flutter: [2023-08-08 13:40:08.522537 | Catcher | INFO] idLike: null
flutter: [2023-08-08 13:40:08.522564 | Catcher | INFO] versionCodename: null
flutter: [2023-08-08 13:40:08.522591 | Catcher | INFO] versionId: 44
flutter: [2023-08-08 13:40:08.522617 | Catcher | INFO] prettyName: GNOME 44 (Flatpak runtime)
flutter: [2023-08-08 13:40:08.522645 | Catcher | INFO] buildId: null
flutter: [2023-08-08 13:40:08.522681 | Catcher | INFO] variant: null
flutter: [2023-08-08 13:40:08.522706 | Catcher | INFO] variantId: null
flutter: [2023-08-08 13:40:08.522729 | Catcher | INFO] machineId: dbfc52975aed46dcab33b235bc7f0310
flutter: [2023-08-08 13:40:08.522755 | Catcher | INFO] 
flutter: [2023-08-08 13:40:08.522780 | Catcher | INFO] ------- APP INFO -------
flutter: [2023-08-08 13:40:08.522811 | Catcher | INFO] environment: release
flutter: [2023-08-08 13:40:08.522838 | Catcher | INFO] version: 3.0.1
flutter: [2023-08-08 13:40:08.523087 | Catcher | INFO] appName: spotube
flutter: [2023-08-08 13:40:08.523130 | Catcher | INFO] buildNumber: 20
flutter: [2023-08-08 13:40:08.523161 | Catcher | INFO] packageName: spotube
flutter: [2023-08-08 13:40:08.523187 | Catcher | INFO] 
flutter: [2023-08-08 13:40:08.523212 | Catcher | INFO] ---------- ERROR ----------
flutter: [2023-08-08 13:40:08.523241 | Catcher | INFO] OAuth authorization error (invalid_token): The access token expired.
flutter: [2023-08-08 13:40:08.523268 | Catcher | INFO] 
flutter: [2023-08-08 13:40:08.523292 | Catcher | INFO] ------- STACK TRACE -------
flutter: [2023-08-08 13:40:08.523510 | Catcher | INFO] #0      Client.send (package:oauth2/src/client.dart:134)
flutter: [2023-08-08 13:40:08.523544 | Catcher | INFO] <asynchronous suspension>
flutter: [2023-08-08 13:40:08.523571 | Catcher | INFO] #1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93)
flutter: [2023-08-08 13:40:08.523597 | Catcher | INFO] <asynchronous suspension>
flutter: [2023-08-08 13:40:08.523622 | Catcher | INFO] #2      SpotifyApiBase._getImpl.<anonymous closure> (package:spotify/src/spotify_base.dart:173)
flutter: [2023-08-08 13:40:08.523655 | Catcher | INFO] <asynchronous suspension>
flutter: [2023-08-08 13:40:08.523681 | Catcher | INFO] #3      SpotifyApiBase._requestWrapper (package:spotify/src/spotify_base.dart:206)
flutter: [2023-08-08 13:40:08.523707 | Catcher | INFO] <asynchronous suspension>
flutter: [2023-08-08 13:40:08.523732 | Catcher | INFO] #4      SpotifyApiBase._getImpl (package:spotify/src/spotify_base.dart:172)
flutter: [2023-08-08 13:40:08.523758 | Catcher | INFO] <asynchronous suspension>
flutter: [2023-08-08 13:40:08.523782 | Catcher | INFO] #5      Pages.getPage (package:spotify/src/endpoints/endpoint_paging.dart:236)
flutter: [2023-08-08 13:40:08.523808 | Catcher | INFO] <asynchronous suspension>
flutter: [2023-08-08 13:40:08.523833 | Catcher | INFO] #6      AlbumQueries.newReleases.<anonymous closure> (package:spotube/services/queries/album.dart:59)
flutter: [2023-08-08 13:40:08.523863 | Catcher | INFO] <asynchronous suspension>
flutter: [2023-08-08 13:40:08.523889 | Catcher | INFO] #7      Retryer.retryOperation (package:fl_query/src/core/mixins/retryer.dart:16)
flutter: [2023-08-08 13:40:08.523915 | Catcher | INFO] <asynchronous suspension>
flutter: [2023-08-08 13:40:08.523940 | Catcher | INFO] #8      CancelableCompleter.complete.<anonymous closure> (package:async/src/cancelable_operation.dart:425)
flutter: [2023-08-08 13:40:08.523969 | Catcher | INFO] <asynchronous suspension>
flutter: [2023-08-08 13:40:08.523995 | Catcher | INFO] 
flutter: [2023-08-08 13:40:08.524020 | Catcher | INFO] ======================================================================
flutter: [2023-08-08 13:40:08.524208 | Catcher | INFO] Report result: true
flutter: [2023-08-08 13:40:08.527223 | Catcher | FINE] Error: 'OAuth authorization error (invalid_token): The access token expired.' has been skipped to due to duplication occurence within 3000 ms.
flutter: [2023-08-08 13:40:08.573382 | Catcher | FINE] Error: 'OAuth authorization error (invalid_token): The access token expired.' has been skipped to due to duplication occurence within 3000 ms.
flutter: [2023-08-08 13:40:08.577371 | Catcher | FINE] Error: 'OAuth authorization error (invalid_token): The access token expired.' has been skipped to due to duplication occurence within 3000 ms.
flutter: [2023-08-08 13:40:08.598105 | Catcher | FINE] Error: 'OAuth authorization error (invalid_token): The access token expired.' has been skipped to due to duplication occurence within 3000 ms.
flutter: [2023-08-08 13:40:08.635088 | Catcher | INFO] Report result: true
flutter: PostgrestException(message: duplicate key value violates unique constraint "tracks_youtube_id_spotify_id_idx", code: 23505, details: Conflict, hint: null)
flutter: #0      PostgrestBuilder._parseResponse (package:postgrest/src/postgrest_builder.dart:323)
flutter: #1      PostgrestBuilder._execute (package:postgrest/src/postgrest_builder.dart:198)
flutter: <asynchronous suspension>
flutter: #2      PostgrestBuilder.then (package:postgrest/src/postgrest_builder.dart:400)
flutter: <asynchronous suspension>
flutter: PostgrestException(message: duplicate key value violates unique constraint "tracks_spotify_id_idx", code: 23505, details: Conflict, hint: null)
flutter: #0      PostgrestBuilder._parseResponse (package:postgrest/src/postgrest_builder.dart:323)
flutter: #1      PostgrestBuilder._execute (package:postgrest/src/postgrest_builder.dart:198)
flutter: <asynchronous suspension>
flutter: #2      PostgrestBuilder.then (package:postgrest/src/postgrest_builder.dart:400)
flutter: <asynchronous suspension>
flutter: [2023-08-08 13:45:28.098871 | Catcher | INFO] ============================== CATCHER LOG ==============================
flutter: [2023-08-08 13:45:28.098932 | Catcher | INFO] Crash occurred on 2023-08-08 13:45:28.098859
flutter: [2023-08-08 13:45:28.098947 | Catcher | INFO] 
flutter: [2023-08-08 13:45:28.098957 | Catcher | INFO] ------- DEVICE INFO -------
flutter: [2023-08-08 13:45:28.098973 | Catcher | INFO] name: GNOME
flutter: [2023-08-08 13:45:28.098986 | Catcher | INFO] version: 44 (Flatpak runtime)
flutter: [2023-08-08 13:45:28.098994 | Catcher | INFO] id: org.gnome.Platform
flutter: [2023-08-08 13:45:28.099003 | Catcher | INFO] idLike: null
flutter: [2023-08-08 13:45:28.099012 | Catcher | INFO] versionCodename: null
flutter: [2023-08-08 13:45:28.099024 | Catcher | INFO] versionId: 44
flutter: [2023-08-08 13:45:28.099045 | Catcher | INFO] prettyName: GNOME 44 (Flatpak runtime)
flutter: [2023-08-08 13:45:28.099065 | Catcher | INFO] buildId: null
flutter: [2023-08-08 13:45:28.099082 | Catcher | INFO] variant: null
flutter: [2023-08-08 13:45:28.099112 | Catcher | INFO] variantId: null
flutter: [2023-08-08 13:45:28.099129 | Catcher | INFO] machineId: dbfc52975aed46dcab33b235bc7f0310
flutter: [2023-08-08 13:45:28.099146 | Catcher | INFO] 
flutter: [2023-08-08 13:45:28.099162 | Catcher | INFO] ------- APP INFO -------
flutter: [2023-08-08 13:45:28.099187 | Catcher | INFO] environment: release
flutter: [2023-08-08 13:45:28.099205 | Catcher | INFO] version: 3.0.1
flutter: [2023-08-08 13:45:28.099221 | Catcher | INFO] appName: spotube
flutter: [2023-08-08 13:45:28.099238 | Catcher | INFO] buildNumber: 20
flutter: [2023-08-08 13:45:28.099261 | Catcher | INFO] packageName: spotube
flutter: [2023-08-08 13:45:28.099284 | Catcher | INFO] 
flutter: [2023-08-08 13:45:28.099300 | Catcher | INFO] ---------- ERROR ----------
flutter: [2023-08-08 13:45:28.099316 | Catcher | INFO] [SponsorBlock] no skip segments found for FQlAEiCb8m0
https://sponsor.ajay.app/api/skipSegments?videoID=FQlAEiCb8m0&category=sponsor&category=selfpromo&category=interaction&category=intro&category=outro&category=music_offtopic&actionType=skip
flutter: [2023-08-08 13:45:28.099367 | Catcher | INFO] 
flutter: [2023-08-08 13:45:28.099384 | Catcher | INFO] ------- STACK TRACE -------
flutter: [2023-08-08 13:45:28.099456 | Catcher | INFO] #0      ProxyPlaylistNotifier.getAndCacheSkipSegments (package:spotube/provider/proxy_playlist/proxy_playlist_provider.dart:522)
flutter: [2023-08-08 13:45:28.099509 | Catcher | INFO] <asynchronous suspension>
flutter: [2023-08-08 13:45:28.099550 | Catcher | INFO] #1      new ProxyPlaylistNotifier.<anonymous closure>.<anonymous closure> (package:spotube/provider/proxy_playlist/proxy_playlist_provider.dart:157)
flutter: [2023-08-08 13:45:28.099585 | Catcher | INFO] <asynchronous suspension>
flutter: [2023-08-08 13:45:28.099613 | Catcher | INFO] 
flutter: [2023-08-08 13:45:28.099655 | Catcher | INFO] ======================================================================
flutter: [2023-08-08 13:45:28.099812 | Catcher | INFO] Report result: true
flutter: [2023-08-08 13:45:28.108222 | Catcher | INFO] Report result: true
flutter: [2023-08-08 13:45:28.125184 | Catcher | FINE] Error: '[SponsorBlock] no skip segments found for FQlAEiCb8m0
https://sponsor.ajay.app/api/skipSegments?videoID=FQlAEiCb8m0&category=sponsor&category=selfpromo&category=interaction&category=intro&category=outro&category=music_offtopic&actionType=skip' has been skipped to due to duplication occurence within 3000 ms.
flutter: [2023-08-08 13:45:28.167245 | Catcher | FINE] Error: '[SponsorBlock] no skip segments found for FQlAEiCb8m0
https://sponsor.ajay.app/api/skipSegments?videoID=FQlAEiCb8m0&category=sponsor&category=selfpromo&category=interaction&category=intro&category=outro&category=music_offtopic&actionType=skip' has been skipped to due to duplication occurence within 3000 ms.
flutter: [2023-08-08 13:45:28.259609 | Catcher | FINE] Error: '[SponsorBlock] no skip segments found for FQlAEiCb8m0
https://sponsor.ajay.app/api/skipSegments?videoID=FQlAEiCb8m0&category=sponsor&category=selfpromo&category=interaction&category=intro&category=outro&category=music_offtopic&actionType=skip' has been skipped to due to duplication occurence within 3000 ms.
flutter: [2023-08-08 13:45:28.309957 | Catcher | FINE] Error: '[SponsorBlock] no skip segments found for FQlAEiCb8m0
https://sponsor.ajay.app/api/skipSegments?videoID=FQlAEiCb8m0&category=sponsor&category=selfpromo&category=interaction&category=intro&category=outro&category=music_offtopic&actionType=skip' has been skipped to due to duplication occurence within 3000 ms.
flutter: [2023-08-08 13:45:28.328147 | Catcher | FINE] Error: '[SponsorBlock] no skip segments found for FQlAEiCb8m0
https://sponsor.ajay.app/api/skipSegments?videoID=FQlAEiCb8m0&category=sponsor&category=selfpromo&category=interaction&category=intro&category=outro&category=music_offtopic&actionType=skip' has been skipped to due to duplication occurence within 3000 ms.
flutter: [2023-08-08 13:45:28.361191 | Catcher | FINE] Error: '[SponsorBlock] no skip segments found for FQlAEiCb8m0
https://sponsor.ajay.app/api/skipSegments?videoID=FQlAEiCb8m0&category=sponsor&category=selfpromo&category=interaction&category=intro&category=outro&category=music_offtopic&actionType=skip' has been skipped to due to duplication occurence within 3000 ms.
flutter: [2023-08-08 13:45:28.400457 | Catcher | FINE] Error: '[SponsorBlock] no skip segments found for FQlAEiCb8m0
https://sponsor.ajay.app/api/skipSegments?videoID=FQlAEiCb8m0&category=sponsor&category=selfpromo&category=interaction&category=intro&category=outro&category=music_offtopic&actionType=skip' has been skipped to due to duplication occurence within 3000 ms.
```

**Comment by systemoperator** [comment]
> You can try the nightly version. There was some fixes applied

It it possible to install the nightly version, using flatpak? Is there a way to download the nightly flatpak asset?

**Comment by KRTirtho** [comment]
Unfortunately no :sweat_smile: 
But there's appimage available (kinda unstable tho)

**Comment by KRTirtho** [comment]
Sorry but the .deb only supports >= debian 12
